name: Publish

on:
  push:
    tags:
      - '**-RELEASE'
      - '**-SNAPSHOT'

permissions:
  contents: read

jobs:
  publish:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'

      - name: Build with Gradle
        uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
        with:
          arguments: build

      - name: Decode signing key ring file
        run: |
          echo "${{ secrets.SIGNING_SECRET_KEY_RING_FILE }}" > ~/.gradle/secring.gpg.b64
          base64 -d ~/.gradle/secring.gpg.b64 > ~/.gradle/secring.gpg

      - name: Get version
        run: | 
          echo "JAR_VERSION=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV
          echo "Version ${{ env.JAR_VERSION }}"

      - name: Publish to maven
        run: ./gradlew publish -P signing.keyId=${{ secrets.SIGNING_KEY_ID }} -P signing.password=${{ secrets.SIGNING_PASSWORD }} -P signing.secretKeyRingFile=$(echo ~/.gradle/secring.gpg)
        env:
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          VERSION: ${{ env.JAR_VERSION }}

